#
# Makefile for the MSM8974 Atmel mXT540S TOUCH drivers.
#

ifdef CONFIG_MACH_MSM8974_EF65S
obj-$(CONFIG_TOUCHSCREEN_ATMEL_MXT_FW30) += ef65/atmel_mxt_fw30.c
else
obj-$(CONFIG_TOUCHSCREEN_ATMEL_MXT_FW30) += msm8974/atmel_mxt_fw30.c
endif

